import { useState, useEffect } from "react";
import { useRoute, Link } from "wouter";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowLeft, CheckCircle2, Code2, Download, FileText, Settings,
  TerminalSquare, Cpu, Box, FolderOpen, Archive, Play,
  Globe, ExternalLink, Copy, Check, Package,
} from "lucide-react";
import { useProject, useProjects } from "@/hooks/use-projects";
import { MediaGallery } from "@/components/project/MediaGallery";
import { useLanguage } from "@/contexts/LanguageContext";
import type { ProjectFile } from "@/data/projects";
import { SEO, projectToJsonLd } from "@/components/SEO";
import { trackProjectView, trackProjectDownload } from "@/lib/analytics";
import CommentSection from "@/components/CommentSection";

type Tab = "overview" | "files" | "media" | "code" | "updates";

const TABS: { id: Tab; label: string; labelAr: string }[] = [
  { id: "overview", label: "Overview", labelAr: "نظرة عامة" },
  { id: "files", label: "Files", labelAr: "الملفات" },
  { id: "media", label: "Media", labelAr: "الوسائط" },
  { id: "code", label: "Code", labelAr: "الكود" },
  { id: "updates", label: "Updates", labelAr: "التحديثات" },
];

const STATUS_COLORS: Record<string, string> = {
  completed: "text-green-400 bg-green-400/10 border-green-400/20",
  active: "text-primary bg-primary/10 border-primary/20",
  archived: "text-muted-foreground bg-muted/30 border-border",
};

const FILE_ICONS: Record<string, React.ElementType> = {
  gerbers: Cpu,
  schematic: FileText,
  model3d: Box,
  source: Code2,
};

const UPDATE_COLORS: Record<string, string> = {
  release: "bg-green-500",
  feature: "bg-primary",
  fix: "bg-orange-400",
  design: "bg-purple-400",
  test: "bg-blue-400",
  note: "bg-muted-foreground",
};

const UPDATE_LABELS: Record<string, string> = {
  release: "RELEASE",
  feature: "FEATURE",
  fix: "FIX",
  design: "DESIGN",
  test: "TEST",
  note: "NOTE",
};

async function downloadAllAsZip(project: NonNullable<ReturnType<typeof useProject>["data"]>) {
  const JSZip = (await import("jszip")).default;
  const zip = new JSZip();
  const folder = zip.folder(project.id) as InstanceType<typeof JSZip>;

  for (const file of project.files) {
    if (file.url) {
      try {
        const res = await fetch(file.url);
        const blob = await res.blob();
        folder.file(file.name, blob);
      } catch {
        folder.file(file.name, `File: ${file.name}\nStatus: Download from project source.`);
      }
    } else {
      folder.file(
        file.name,
        `Project: ${project.title}\nFile: ${file.name}\nType: ${file.type}\nDescription: ${file.description}\n\nContact to obtain this file.`
      );
    }
  }

  folder.file(
    "README.txt",
    `${project.title}\n${"=".repeat(project.title.length)}\n\n${project.description}\n\nGitHub: ${project.githubUrl}\n\nGenerated by INFINITY.TECH`
  );

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${project.id}-files.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function FileCard({ file }: { file: ProjectFile }) {
  const Icon = FILE_ICONS[file.type] || FileText;
  const typeLabel = { gerbers: "Gerber ZIP", schematic: "Schematic", model3d: "3D Model", source: "Source Code" }[file.type];

  return (
    <div className="flex items-center justify-between p-4 rounded-xl bg-background border border-border hover:border-primary/30 transition-colors group">
      <div className="flex items-center gap-3 min-w-0">
        <div className="w-9 h-9 rounded-lg bg-card border border-border flex items-center justify-center flex-shrink-0 group-hover:border-primary/30 transition-colors">
          <Icon className="w-4 h-4 text-primary" />
        </div>
        <div className="min-w-0">
          <p className="text-sm font-mono font-medium text-foreground truncate">{file.name}</p>
          <p className="text-xs text-muted-foreground mt-0.5">{file.description}</p>
        </div>
      </div>
      <div className="flex items-center gap-3 ml-4 flex-shrink-0">
        <span className="text-xs font-mono text-muted-foreground hidden sm:block">{file.size}</span>
        <span className="text-[9px] font-mono font-bold tracking-widest uppercase text-muted-foreground/60 border border-border px-1.5 py-0.5 rounded hidden sm:block">
          {typeLabel}
        </span>
        {file.url ? (
          <a
            href={file.url}
            download
            className="w-8 h-8 rounded-lg bg-primary/10 border border-primary/30 flex items-center justify-center text-primary hover:bg-primary hover:text-primary-foreground transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
          </a>
        ) : (
          <div className="w-8 h-8 rounded-lg bg-border/30 flex items-center justify-center text-muted-foreground/40 cursor-not-allowed" title="File not uploaded yet">
            <Download className="w-3.5 h-3.5" />
          </div>
        )}
      </div>
    </div>
  );
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button
      onClick={copy}
      className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-medium text-muted-foreground hover:text-foreground border border-border hover:border-primary/30 transition-colors"
    >
      {copied ? <Check className="w-3 h-3 text-primary" /> : <Copy className="w-3 h-3" />}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

export function ProjectDetail() {
  const [, params] = useRoute("/projects/:id");
  const id = params?.id || "";
  const { data: project, isLoading, error } = useProject(id);
  const { data: allProjects } = useProjects();
  const relatedProjects = allProjects?.filter(p => p.id !== id).slice(0, 3) ?? [];

  const [activeTab, setActiveTab] = useState<Tab>("overview");
  const [isDownloading, setIsDownloading] = useState(false);
  const { lang, setLang, isRTL, t } = useLanguage();

  useEffect(() => {
    if (id) trackProjectView(id, id);
  }, [id]);

  if (isLoading) {
    return (
      <div className="min-h-screen pt-32 pb-24 flex justify-center items-center border-t border-primary/30">
        <div className="w-8 h-8 rounded-full border-2 border-primary border-t-transparent animate-spin" />
      </div>
    );
  }

  if (error || !project) {
    return (
      <div className="min-h-screen pt-32 pb-24 flex flex-col items-center justify-center text-center px-4 border-t border-primary/30">
        <TerminalSquare className="w-16 h-16 text-muted-foreground mb-4 opacity-50" />
        <h1 className="text-2xl font-bold tracking-tighter text-foreground mb-2">Project Not Found</h1>
        <p className="text-muted-foreground mb-8">The requested project data is unavailable.</p>
        <Link href="/projects" className="px-6 py-3 rounded-xl bg-card border border-border text-foreground hover:bg-white/5 transition-colors">
          Return to Projects
        </Link>
      </div>
    );
  }

  const handleDownloadAll = async () => {
    setIsDownloading(true);
    trackProjectDownload(project.id);
    try {
      await downloadAllAsZip(project);
    } finally {
      setIsDownloading(false);
    }
  };

  const publicUpdates = project.updates.filter(u => !u.adminOnly);

  return (
    <div className="min-h-screen w-full pt-28 pb-24 relative" dir="ltr">
      <SEO
        title={t(project.title, project.titleAr || project.title)}
        description={t(project.description, project.descriptionAr || project.description)}
        keywords={project.tags.join(", ")}
        lang={lang}
        type="article"
        jsonLd={projectToJsonLd({
          id: project.id,
          title: project.title,
          description: project.description,
          tags: project.tags,
          status: project.status,
          createdAt: project.createdAt,
          updatedAt: project.updatedAt,
          githubUrl: project.githubUrl,
        })}
      />
      <div className="absolute top-0 left-0 right-0 h-px bg-primary/30 shadow-[0_0_20px_rgba(34,211,238,0.3)]" />

      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Top bar */}
        <div className="flex items-center justify-between mb-8 flex-wrap gap-3">
          <Link href="/projects" className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-primary transition-colors">
            <ArrowLeft className={`w-4 h-4 ${isRTL ? "rotate-180" : ""}`} />
            {t("Back to Projects", "العودة للمشاريع")}
          </Link>
          <div className="flex items-center gap-3">
            {/* Language Toggle */}
            <div className="flex items-center bg-card border border-border rounded-lg p-0.5 text-xs font-mono font-bold">
              <button
                onClick={() => setLang("en")}
                className={`px-3 py-1.5 rounded-md transition-colors ${lang === "en" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`}
              >
                EN
              </button>
              <button
                onClick={() => setLang("ar")}
                className={`px-3 py-1.5 rounded-md transition-colors ${lang === "ar" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground"}`}
              >
                عربي
              </button>
            </div>
            {/* Download All ZIP */}
            <button
              onClick={handleDownloadAll}
              disabled={isDownloading}
              className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground text-sm font-semibold hover:opacity-90 active:scale-95 transition-all disabled:opacity-60"
            >
              {isDownloading ? (
                <div className="w-4 h-4 rounded-full border-2 border-primary-foreground/40 border-t-primary-foreground animate-spin" />
              ) : (
                <Package className="w-4 h-4" />
              )}
              {t("Download ZIP", "تحميل ZIP")}
            </button>
          </div>
        </div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
          {/* Header */}
          <div className="mb-8">
            <div className="flex flex-wrap items-center gap-2 mb-4">
              {project.tags.map(tag => (
                <span key={tag} className="px-2 py-1 text-[10px] uppercase font-mono font-medium rounded bg-primary/10 text-primary border border-primary/20">
                  {tag}
                </span>
              ))}
              <span className={`px-2 py-1 text-[10px] uppercase font-mono font-bold rounded border ${STATUS_COLORS[project.status]}`}>
                {project.status}
              </span>
            </div>
            <h1 className="fluid-h1 font-black tracking-tighter text-foreground mb-3">
              {t(project.title, project.titleAr)}
            </h1>
            <p className="text-lg text-muted-foreground leading-relaxed max-w-2xl">
              {t(project.description, project.descriptionAr)}
            </p>
          </div>

          {/* Hero image placeholder */}
          <div className="w-full h-48 md:h-64 rounded-2xl bg-gradient-to-br from-card to-background border border-border mb-8 relative overflow-hidden flex items-center justify-center group">
            <div
              className="absolute inset-0 opacity-25"
              style={{ backgroundImage: `url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iMiIgY3k9IjIiIHI9IjEiIGZpbGw9InJnYmEoMzQsMjExLDIzOCwwLjQpIi8+PC9zdmc+")` }}
            />
            <div className="absolute inset-0 bg-gradient-to-t from-background/60 to-transparent" />
            <Settings className="w-12 h-12 text-primary/20 group-hover:text-primary/40 transition-colors duration-300" />
            {/* Watermark */}
            <div className="absolute bottom-4 right-4 pointer-events-none">
              <span className="text-[11px] font-mono font-bold tracking-widest uppercase" style={{ color: "rgba(34,211,238,0.3)", transform: "rotate(-8deg)", display: "block", transformOrigin: "bottom right" }}>
                INFINITY.TECH
              </span>
            </div>
          </div>

          {/* Tab Navigation */}
          <div className="border-b border-border mb-8">
            <div className="flex gap-0 overflow-x-auto scrollbar-none">
              {TABS.map(tab => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`relative px-5 py-3 text-sm font-medium whitespace-nowrap transition-colors flex-shrink-0 ${
                    activeTab === tab.id
                      ? "text-foreground"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {t(tab.label, tab.labelAr)}
                  {activeTab === tab.id && (
                    <motion.div
                      layoutId="tab-indicator"
                      className="absolute bottom-0 left-0 right-0 h-0.5 bg-primary"
                      transition={{ duration: 0.2, ease: "easeInOut" }}
                    />
                  )}
                </button>
              ))}
            </div>
          </div>

          {/* Tab Content */}
          <AnimatePresence mode="wait">
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.18 }}
            >
              {/* ── OVERVIEW ── */}
              {activeTab === "overview" && (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-10">
                  <div className="lg:col-span-2 space-y-10">
                    <section>
                      <p className="text-[11px] font-semibold text-primary uppercase tracking-[0.2em] mb-3">
                        {t("Overview", "نظرة عامة")}
                      </p>
                      <p className="text-muted-foreground leading-relaxed">
                        {t(project.overview, project.overviewAr)}
                      </p>
                    </section>

                    <section>
                      <p className="text-[11px] font-semibold text-primary uppercase tracking-[0.2em] mb-4">
                        {t("Problem & Solution", "المشكلة والحل")}
                      </p>
                      <div className="space-y-4">
                        <div className="p-5 rounded-xl bg-card border border-border">
                          <h3 className="text-sm font-bold text-foreground mb-2 flex items-center gap-2">
                            <span className="w-5 h-5 rounded-full bg-border flex items-center justify-center text-[10px]">!</span>
                            {t("The Challenge", "التحدي")}
                          </h3>
                          <p className="text-sm text-muted-foreground leading-relaxed">
                            {t(project.problem, project.problemAr)}
                          </p>
                        </div>
                        <div className="p-5 rounded-xl bg-card border border-primary/20 shadow-[0_0_15px_rgba(34,211,238,0.04)]">
                          <h3 className="text-sm font-bold text-primary mb-2 flex items-center gap-2">
                            <CheckCircle2 className="w-4 h-4" />
                            {t("The Solution", "الحل")}
                          </h3>
                          <p className="text-sm text-muted-foreground leading-relaxed">
                            {t(project.solution, project.solutionAr)}
                          </p>
                        </div>
                      </div>
                    </section>
                  </div>

                  <div className="space-y-8">
                    {/* Quick links */}
                    <div className="p-5 rounded-2xl bg-card border border-border">
                      <p className="text-[11px] font-semibold text-primary uppercase tracking-[0.2em] mb-4">
                        {t("Quick Access", "وصول سريع")}
                      </p>
                      <div className="space-y-2">
                        {[
                          { label: t("Files & Gerbers", "الملفات والغيربرز"), tab: "files" as Tab, icon: FolderOpen },
                          { label: t("Media Gallery", "معرض الوسائط"), tab: "media" as Tab, icon: Play },
                          { label: t("Source Code", "الكود المصدري"), tab: "code" as Tab, icon: Code2 },
                          { label: t("Version History", "سجل الإصدارات"), tab: "updates" as Tab, icon: Archive },
                        ].map(({ label, tab, icon: Icon }) => (
                          <button
                            key={tab}
                            onClick={() => setActiveTab(tab)}
                            className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-lg bg-background border border-border hover:border-primary/30 text-sm text-muted-foreground hover:text-foreground transition-colors text-left"
                          >
                            <Icon className="w-4 h-4 text-primary flex-shrink-0" />
                            {label}
                          </button>
                        ))}
                        <a
                          href={project.githubUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-lg bg-background border border-border hover:border-primary/30 text-sm text-muted-foreground hover:text-foreground transition-colors"
                        >
                          <Globe className="w-4 h-4 text-primary flex-shrink-0" />
                          {t("View on GitHub", "عرض على GitHub")}
                          <ExternalLink className="w-3 h-3 ml-auto" />
                        </a>
                      </div>
                    </div>

                    {/* Timeline */}
                    <div>
                      <p className="text-[11px] font-semibold text-primary uppercase tracking-[0.2em] mb-4">
                        {t("Development Timeline", "الجدول الزمني")}
                      </p>
                      <div className="relative pl-5 border-l border-border space-y-6">
                        {project.timeline.map((item, idx) => (
                          <div key={idx} className="relative">
                            <div className={`absolute -left-[21px] top-1 w-2.5 h-2.5 rounded-full bg-background border-2 ${idx === 0 ? "border-primary" : "border-border"}`} />
                            <span className="text-xs font-mono text-primary font-bold">{item.date}</span>
                            <h4 className="text-sm font-bold tracking-tight text-foreground mt-0.5 mb-0.5">{item.title}</h4>
                            <p className="text-xs text-muted-foreground">{item.desc}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* ── FILES ── */}
              {activeTab === "files" && (
                <div className="space-y-6">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-[11px] font-semibold text-primary uppercase tracking-[0.2em] mb-1">
                        {t("Project Files", "ملفات المشروع")}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        {project.files.length} {t("files available", "ملف متاح")}
                      </p>
                    </div>
                    <button
                      onClick={handleDownloadAll}
                      disabled={isDownloading}
                      className="flex items-center gap-2 px-4 py-2 rounded-lg border border-primary/40 text-primary text-sm font-medium hover:bg-primary/10 transition-colors disabled:opacity-60"
                    >
                      {isDownloading ? (
                        <div className="w-4 h-4 rounded-full border-2 border-primary/40 border-t-primary animate-spin" />
                      ) : (
                        <Archive className="w-4 h-4" />
                      )}
                      {t("Download All as ZIP", "تحميل الكل كـ ZIP")}
                    </button>
                  </div>

                  <div className="space-y-3">
                    {project.files.map(file => (
                      <FileCard key={file.id} file={file} />
                    ))}
                  </div>

                  {project.files.length === 0 && (
                    <div className="py-16 flex flex-col items-center justify-center border border-dashed border-border rounded-xl text-center">
                      <FolderOpen className="w-10 h-10 text-muted-foreground/30 mb-3" />
                      <p className="text-sm text-muted-foreground">{t("No files uploaded yet", "لا توجد ملفات بعد")}</p>
                    </div>
                  )}

                  <div className="p-4 rounded-xl bg-primary/5 border border-primary/15 text-sm text-muted-foreground">
                    <p className="font-medium text-primary mb-1">{t("File Notice", "ملاحظة حول الملفات")}</p>
                    {t(
                      "Files marked with a disabled download button are not yet publicly hosted. Contact via the contact page to request access.",
                      "الملفات التي تحتوي على زر تنزيل معطل غير مستضافة بعد. تواصل عبر صفحة التواصل للحصول على الوصول."
                    )}
                  </div>
                </div>
              )}

              {/* ── MEDIA ── */}
              {activeTab === "media" && (
                <MediaGallery media={project.media} />
              )}

              {/* ── CODE ── */}
              {activeTab === "code" && (
                <div className="space-y-6">
                  <div className="flex items-center justify-between">
                    <p className="text-[11px] font-semibold text-primary uppercase tracking-[0.2em]">
                      {t("Implementation Snippet", "مقطع التنفيذ")}
                    </p>
                    <a
                      href={project.githubUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"
                    >
                      <Globe className="w-4 h-4" />
                      {t("Full source on GitHub", "الكود الكامل على GitHub")}
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </div>

                  <div className="rounded-xl border border-border bg-background overflow-hidden">
                    <div className="flex items-center justify-between px-4 py-2 border-b border-border bg-card">
                      <div className="flex items-center gap-3">
                        <div className="flex gap-1.5">
                          <div className="w-3 h-3 rounded-full bg-border" />
                          <div className="w-3 h-3 rounded-full bg-border" />
                          <div className="w-3 h-3 rounded-full bg-primary/30" />
                        </div>
                        <span className="text-xs font-mono text-muted-foreground lowercase">{project.language}</span>
                      </div>
                      <CopyButton text={project.codeSnippet} />
                    </div>
                    <pre className="p-5 overflow-x-auto text-sm font-mono text-[#E6EDF3] leading-relaxed">
                      <code>{project.codeSnippet}</code>
                    </pre>
                  </div>

                  <div className="p-5 rounded-xl bg-card border border-border">
                    <p className="text-[11px] font-semibold text-primary uppercase tracking-[0.2em] mb-3">
                      {t("Tech Stack", "التقنيات المستخدمة")}
                    </p>
                    <div className="flex flex-wrap gap-2">
                      {project.tags.map(tag => (
                        <span key={tag} className="px-3 py-1 text-xs font-mono rounded-lg bg-background border border-border text-muted-foreground">
                          {tag}
                        </span>
                      ))}
                      <span className="px-3 py-1 text-xs font-mono rounded-lg bg-background border border-border text-muted-foreground capitalize">
                        {project.language}
                      </span>
                    </div>
                  </div>
                </div>
              )}

              {/* ── UPDATES ── */}
              {activeTab === "updates" && (
                <div className="space-y-6">
                  <div>
                    <p className="text-[11px] font-semibold text-primary uppercase tracking-[0.2em] mb-1">
                      {t("Version History", "سجل الإصدارات")}
                    </p>
                    <p className="text-sm text-muted-foreground">
                      {publicUpdates.length} {t("public entries", "إدخالات عامة")}
                    </p>
                  </div>

                  {publicUpdates.length > 0 ? (
                    <div className="relative pl-6 border-l border-border space-y-8">
                      {publicUpdates.map((update, idx) => (
                        <motion.div
                          key={update.id}
                          initial={{ opacity: 0, x: -10 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: idx * 0.06 }}
                          className="relative"
                        >
                          <div className={`absolute -left-[25px] top-1.5 w-3 h-3 rounded-full ${UPDATE_COLORS[update.type]}`} />
                          <div className="flex flex-wrap items-center gap-2 mb-2">
                            <span className="text-xs font-mono font-bold text-primary">{update.version}</span>
                            <span className={`text-[9px] font-mono font-bold tracking-widest uppercase px-1.5 py-0.5 rounded border ${
                              update.type === "release" ? "text-green-400 border-green-400/30 bg-green-400/10" :
                              update.type === "feature" ? "text-primary border-primary/30 bg-primary/10" :
                              update.type === "fix" ? "text-orange-400 border-orange-400/30 bg-orange-400/10" :
                              "text-muted-foreground border-border"
                            }`}>
                              {UPDATE_LABELS[update.type]}
                            </span>
                            <span className="text-xs font-mono text-muted-foreground/60">{update.date}</span>
                          </div>
                          <h4 className="text-sm font-bold tracking-tight text-foreground mb-1">
                            {t(update.title, update.titleAr)}
                          </h4>
                          <p className="text-sm text-muted-foreground leading-relaxed">
                            {t(update.desc, update.descAr)}
                          </p>
                        </motion.div>
                      ))}
                    </div>
                  ) : (
                    <div className="py-16 flex flex-col items-center justify-center border border-dashed border-border rounded-xl text-center">
                      <Archive className="w-10 h-10 text-muted-foreground/30 mb-3" />
                      <p className="text-sm text-muted-foreground">{t("No public updates yet", "لا توجد تحديثات عامة بعد")}</p>
                    </div>
                  )}
                </div>
              )}
            </motion.div>
          </AnimatePresence>
        </motion.div>

        {/* Related Projects */}
        {relatedProjects.length > 0 && (
          <div className="mt-20 pt-16 border-t border-white/5">
            <div className="flex items-center gap-3 mb-8">
              <span className="w-8 h-px bg-primary inline-block" />
              <h2 className="text-2xl font-bold tracking-tighter text-foreground">
                {t("More Projects", "مشاريع أخرى")}
              </h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
              {relatedProjects.map((related, idx) => (
                <motion.div
                  key={related.id}
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: idx * 0.08 }}
                  whileHover={{ y: -3 }}
                >
                  <Link
                    href={`/projects/${related.id}`}
                    className="block h-full p-5 rounded-2xl bg-card border border-border hover:border-primary/30 transition-colors duration-200 group"
                  >
                    <div className="flex flex-wrap gap-1.5 mb-3">
                      {related.tags.slice(0, 2).map(tag => (
                        <span key={tag} className="px-2 py-0.5 text-[10px] uppercase font-mono font-medium rounded bg-primary/10 text-primary border border-primary/20">
                          {tag}
                        </span>
                      ))}
                    </div>
                    <h3 className="text-sm font-bold tracking-tight text-foreground mb-2 group-hover:text-primary transition-colors">
                      {t(related.title, related.titleAr)}
                    </h3>
                    <p className="text-xs text-muted-foreground leading-relaxed line-clamp-2 mb-4">
                      {t(related.description, related.descriptionAr)}
                    </p>
                    <span className="text-xs font-medium text-primary">
                      {t("View Project →", "عرض المشروع ←")}
                    </span>
                  </Link>
                </motion.div>
              ))}
            </div>
          </div>
        )}

        {/* Comments */}
        <CommentSection projectId={project.id} />
      </div>
    </div>
  );
}
